Add newsweek clone
jabichris/Newsweek-clone pull request #3
Opened 2020-02-12 20:22 UTC by jabichris

#### What does this PR do?
This PR consists of building a clone of the Newsweek webpage.

2020-02-13 11:45 UTC, nikasulo requested changes
# Really great work so far @jabichris 
Your project is coming together very nicely :100: Please consider my comments below, make appropriate changes and request another review. I wish you all the best :+1: 

#### Navigation bar
Your navigation bar is a little buggy, the positioning of elements, and padding of the navigation are in a little twist. Consider comparing what the original site looks like(including but not limited to responsiveness) to yours and make any appropriate changes. Pay attention to the mobile versions of the navigation bar :ok_hand: 
#### Horizontal Scroll
You seem to have a little bug with one of the elements of the page, shooting out beyond the browser's maximum width. This may be as a result of a margin or padding you have set up. One of the easiest ways I have found to correct this issue is to set the default `box-sizing` property to `border-box` as follows `*{box-sizing: border-box}`. Please read some more about it [here](https://developer.mozilla.org/en-US/docs/Web/CSS/box-sizing).

#### In the magazine, Subscribe & Newsletter
Please note that these sections is not responding as they should especially on the tablet screen size, look into it thoroughly and make the appropriate changes :+1: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

2020-02-13 17:57 UTC, mosesogwo requested changes
**Hi @jabichris, well done:clap:. Let us take care of the following:**

**On Large Screens**
1. In the header, lets have some top padding.
2. The Sign In element is not well aligned.
![image](https://user-images.githubusercontent.com/46611870/74462496-9b8a2300-4e90-11ea-8a2c-6428dd582df5.png)

3. In the Magazine section, images are not properly scaled.

**On Medium Screens:**
4. Reduce the height of the header to look like the original. Take care of the SIgn In element.
![image](https://user-images.githubusercontent.com/46611870/74462737-04719b00-4e91-11ea-89d6-9b97b73218db.png)
5. Check the left margin of the page
6. Images are not properly scaled in the **"In the Magazine"** section.
7. Editor's Pick should be aligned 2 per row
8. Check the right margin of the **US, World, Business ...** section

**On small screens:**
9. The order of sections in the sections before **"In the magazine"** is not maintained as it is in the original page. For example, Top story should come first. You can use css order property to achieve this.

**Other issues**
- Also, check the **US, World, Business ...**, font-weight of all article titles should be uniform.
- You have so many validation errors in your markup. You should validate your markup here https://validator.w3.org/#validate_by_upload 

**Kindly address the foregoing and submit another code review request.**

**Cheers:stars:**

2020-02-13 21:59 UTC, euqueme requested changes
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @jabichris :handshake: 

### Thank you for doing the changes requested by the previous reviewers, your page looks really good :medal_sports:  

### there is still some work to do :hammer:  :bowing_woman: 

### Bootstrap Usage

- [x] I'm sorry this wasn't pointed out to you before by the previous reviewers but this project is all about using bootstrap, so, please remove all of these selectors  from your CSS and use the equivalent bootstrap classes in your HTML file

- padding: 0; (4 ocurrences )
- padding-top: 0; (1 ocurrence )
- margin: 0; (6 ocurrences )
- margin-left: 0; (4 ocurrences )
- margin-right: 0 (3 ocurrences )
- margin-bottom: 0 (2 ocurrences )
- color: black; (6 ocurrences in yor CSS file)
- color: white; (6 ocurrences )
- color: red; (1 ocurrence)
- background-color: white; (4 ocurrences )
- display: none; (6 ocurrences )
- display: inline; (8 ocurrences)
- display: block; (11 ocurrences)
- display: flex; (11 ocurrences )
- display: block; (6 ocurrences)
- justify-content: center; (1 ocurrence )
- justify-content: space-between; (1 ocurrence )
- text-decoration: none; (1 ocurrence)
- text-align: center; (5 ocurrences )
- text-transform: none; (1 ocurrence )
- text-transform: uppercase; (10 ocurrences )
- border-top: 0; (1 ocurrence )
- flex-direction: column; (1 ocurrence)
- font-weight: bold (2 ocurrences)
- flex-wrap: wrap; (2 ocurrence )

## Small Screens

**Navbar**

- [x] The NEWSWEEK logo should be centered vertically, yours is on the top of the navbar

- Yours
![image](https://user-images.githubusercontent.com/52209067/74476309-b77ccd00-4e6e-11ea-808a-7ce9256b5801.png)

- Original

![image](https://user-images.githubusercontent.com/52209067/74476343-c2376200-4e6e-11ea-82c1-29fc3eeae37a.png)

**Section Positioning**

- [x] please follow the structure for the first 4 sections in this screen size as it was mention before by the previous reviewer:

1. TOP STORY
2. MORE STORIES
3. CULTURE & TRAVEL
4. FEATURED STORIES

- Yours

![image](https://user-images.githubusercontent.com/52209067/74478873-d762bf80-4e73-11ea-92fe-c8fba0d0b657.png)

- Original

![image](https://user-images.githubusercontent.com/52209067/74478900-e47fae80-4e73-11ea-8172-f6758fe16fcd.png)

**MOORE STORIES**

- [x] The image of the articles should take 60% of the screen width and the headline and content only 40%

- Yours

![image](https://user-images.githubusercontent.com/52209067/74479127-43ddbe80-4e74-11ea-8e36-ddd386b728ac.png)

- Original

![image](https://user-images.githubusercontent.com/52209067/74479165-535d0780-4e74-11ea-99db-6f37753f4cb8.png)

**OPINION**

- [x] the image of the articles should take only 25%  of the screen width and the headline and content 75%

- Yours

![image](https://user-images.githubusercontent.com/52209067/74479478-d2524000-4e74-11ea-9828-0f764b93d779.png)

- Original

![image](https://user-images.githubusercontent.com/52209067/74479498-df6f2f00-4e74-11ea-8dcd-502b3c47ff25.png)

**LATEST NEWS**

- [x] the image of the articles should take only 60%  of the screen width and the headline only 40%

- Yours
![image](https://user-images.githubusercontent.com/52209067/74479619-11809100-4e75-11ea-8803-bfb66a61f24c.png)

- Original

![image](https://user-images.githubusercontent.com/52209067/74479648-23623400-4e75-11ea-892c-5b46f2383898.png)

**U.S, World, Business, Tech & Science, Culture and Sports**

- [x] The image of the aside articles of these sections should take 60% of the screen width and the headline only 40%

- Yours

![image](https://user-images.githubusercontent.com/52209067/74479799-72a86480-4e75-11ea-9375-9a96730b17d9.png)

- Original

![image](https://user-images.githubusercontent.com/52209067/74479852-85229e00-4e75-11ea-98e3-1811c3a7207a.png)

**SUBSCRIBE**

- [x] the overlapping magazines have to have the same size, also the content has to be centered in the page

- Yours

![image](https://user-images.githubusercontent.com/52209067/74479983-bbf8b400-4e75-11ea-8b87-5628dc067a76.png)

- Original

![image](https://user-images.githubusercontent.com/52209067/74480032-cd41c080-4e75-11ea-8323-41776b41b7c6.png)

**NEWSLETTER**

- [x] The NEWSLETTER section starts with an image

- Yours

![image](https://user-images.githubusercontent.com/52209067/74480125-f9f5d800-4e75-11ea-8abb-9f83c0edf73a.png)

- Original

![image](https://user-images.githubusercontent.com/52209067/74480173-0da13e80-4e76-11ea-984b-7b31bf1024a3.png)

## Medium Screens

**NEWSLETTER**

- [x] the image takes 25% of the page width and the content 75%, the content also should be aligned at the left 

- Yours

![image](https://user-images.githubusercontent.com/52209067/74480695-07f82880-4e77-11ea-904e-085fc2d689a7.png)

- Original

![image](https://user-images.githubusercontent.com/52209067/74480727-16dedb00-4e77-11ea-80c8-d33b531d9166.png)

## Big Screens

**Editor's Pick**

- [x]  The articles should be placed in 4 columns, yours are in 2

- Yours

![image](https://user-images.githubusercontent.com/52209067/74481183-e0559000-4e77-11ea-9255-2ad943ca685e.png)

- Original

![image](https://user-images.githubusercontent.com/52209067/74481215-f2373300-4e77-11ea-8493-fbd8cd63b672.png)

**SUBSCRIBE ans NEWSLETTER**

- [x] should be in the same row, SUBSCRIBE taking 70% of the screen width and NEWSLETTER 30%

- Yours

![image](https://user-images.githubusercontent.com/52209067/74481392-40e4cd00-4e78-11ea-97f6-1730031b7eaf.png)

- Original

![image](https://user-images.githubusercontent.com/52209067/74481421-4f32e900-4e78-11ea-9a9e-a0208b57a303.png)

## All Screen sizes

**OPINION**

- [x] the images should have half of the size they have now

- Yours

![image](https://user-images.githubusercontent.com/52209067/74480921-6c1aec80-4e77-11ea-89f2-12068648db59.png)

- Original

![image](https://user-images.githubusercontent.com/52209067/74480959-789f4500-4e77-11ea-907a-ea1a6c965bdd.png)

**Footer**

- [x] the twitter logo is missing

- Yours

![image](https://user-images.githubusercontent.com/52209067/74480285-3de8dd00-4e76-11ea-81a3-995f2137f862.png)

- Original

![image](https://user-images.githubusercontent.com/52209067/74480318-4b05cc00-4e76-11ea-88cb-52f049b90320.png)

## General

- [x] remove all inline styling I've left comments where all inline styling was found (17 lines) :arrow_down: 

- [x] fix the 95 errors detected by the [HTML validator ](https://validator.w3.org/#validate_by_upload)

![image](https://user-images.githubusercontent.com/52209067/74481752-e6983c00-4e78-11ea-802c-ff6055c344aa.png)

### That's It! :raised_hands: 

### Please :pray: make the changes :memo: and submit back for a code review when you are done :rocket: 

Happy Coding! :woman_technologist: 

Any question? reach to me on slack **@ Maru**

PROJECT STATUS: REQUESTED CHANGES :traffic_light:

2020-02-13 21:59 UTC, euqueme commented on index.html
> +                style="position: static; left: 0; top: 0; width: auto;"
Remove the inline styling on line #407, all styling should be in the CSS file

2020-02-13 21:59 UTC, euqueme commented on index.html
> +                  style="padding-left: 15px; padding-right: 15px;"
Remove the inline styling on line #1205, all styling should be in the CSS file

2020-02-13 21:59 UTC, euqueme commented on index.html
> +                  style="padding-left: 15px; padding-right: 15px;"
Remove the inline styling on line #1221, all styling should be in the CSS file

2020-02-13 21:59 UTC, euqueme commented on index.html
> +                            <picture style="padding-bottom: 66.7506%;">
Remove the inline styling on line #468, all styling should be in the CSS file

2020-02-13 21:59 UTC, euqueme commented on index.html
> +                            <picture style="padding-bottom: 66.7506%;">
Remove the inline styling on line #500, all styling should be in the CSS file

2020-02-13 21:59 UTC, euqueme commented on index.html
> +                              <picture style="padding-bottom: 66.6667%;">
Remove the inline styling on line #599, all styling should be in the CSS file

2020-02-13 21:59 UTC, euqueme commented on index.html
> +                              <picture style="padding-bottom: 66.6667%;">
Remove the inline styling on line #621, all styling should be in the CSS file

2020-02-13 21:59 UTC, euqueme commented on index.html
> +                              <picture style="padding-bottom: 66.6667%;">
Remove the inline styling on line #642, all styling should be in the CSS file

2020-02-13 21:59 UTC, euqueme commented on index.html
> +                              <picture style="padding-bottom: 66.6667%;">
Remove the inline styling on line #664, all styling should be in the CSS file

2020-02-13 21:59 UTC, euqueme commented on index.html
> +                              <picture style="padding-bottom: 66.6667%;">
Remove the inline styling on line #685, all styling should be in the CSS file

2020-02-13 21:59 UTC, euqueme commented on index.html
> +                              <picture style="padding-bottom: 66.6667%;">
Remove the inline styling on line #707, all styling should be in the CSS file

2020-02-13 21:59 UTC, euqueme commented on index.html
> +                              <picture style="padding-bottom: 66.6667%;">
Remove the inline styling on line #731, all styling should be in the CSS file

2020-02-13 21:59 UTC, euqueme commented on index.html
> +                              <picture style="padding-bottom: 66.6667%;">
Remove the inline styling on line #753, all styling should be in the CSS file

2020-02-13 21:59 UTC, euqueme commented on index.html
> +                              <picture style="padding-bottom: 66.6667%;">
Remove the inline styling on line #775, all styling should be in the CSS file

2020-02-13 21:59 UTC, euqueme commented on index.html
> +                              <picture style="padding-bottom: 66.6667%;">
Remove the inline styling on line #797, all styling should be in the CSS file

2020-02-13 21:59 UTC, euqueme commented on index.html
> +                          clas
Remove the inline styling on line #2397, all styling should be in the CSS file

2020-02-13 21:59 UTC, euqueme commented on index.html
> +                          clas
Remove the inline styling on line #2489, all styling should be in the CSS file

2020-02-13 21:59 UTC, euqueme commented on README.md
> +#### Link to live view
Add a Live View of your page or remove this line (#7)

2020-02-14 18:59 UTC, pelzolga123 requested changes
Project requires changes.

2020-02-14 18:59 UTC, pelzolga123 commented
## Hi Christian! ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
### Your did amazing job so far :+1: 
But still not everything looks correctly:
* [ ] Tablet version looks messed up right now, everything is displayed in one column:
![image](https://user-images.githubusercontent.com/20416431/74559044-24c25800-4f6c-11ea-8b84-080e9892ef47.png)
* [ ] Next section in large version still looks not like original one, `newsletter` part is smaller then `subscribe` part:
![image](https://user-images.githubusercontent.com/20416431/74559157-681cc680-4f6c-11ea-96fd-f0057a10d5c2.png)
Original:
![image](https://user-images.githubusercontent.com/20416431/74559198-7ec31d80-4f6c-11ea-952c-3ea15952c38b.png)

### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

2020-02-14 23:27 UTC, addod19 requested changes
## Status: Require changes 🔴

Hi @jabichris, you have done a great job. 👍 However, we still need some fixing in the ```Tablet mode``` as pointed out by the previous reviewer. Find comment below: 😄 
- ```In the magazine``` section need padding
![padd](https://user-images.githubusercontent.com/46388113/74575957-e7b49080-4f80-11ea-9080-1b5611dd3ba6.PNG)
- ```Editor Pick``` section span 2 columns but currently, we have four columns
![edit](https://user-images.githubusercontent.com/46388113/74576025-234f5a80-4f81-11ea-80d3-5b7a73b22c25.PNG)
```Original version```
![edit1](https://user-images.githubusercontent.com/46388113/74576057-4974fa80-4f81-11ea-9273-c4b9a731e518.PNG)

Kindly make these changes and submit another code review 🙂 
Happy coding 💻 
Daniel Larbi Addo

2020-02-17 17:25 UTC, addod19 requested changes
## Status: Require changes 🔴

Hi @jabichris, great work fixing the changes. 👍 However, ```Editors pick``` on ```Smalll screen``` should take the full width. Currently, it looks this way 🙂 
- ![fixnow](https://user-images.githubusercontent.com/46388113/74674880-34c77b00-51aa-11ea-9e63-0f2cef90ccc1.PNG)
```Original version```
![now](https://user-images.githubusercontent.com/46388113/74674935-53c60d00-51aa-11ea-960b-5c58cf20fd7f.PNG)

Kindly make this change and submit code review 😄We are almost there
Happy coding 💻

2020-02-17 19:56 UTC, addod19 approved these changes
## Status: Approved 🎈 

**Congratulations** @jabichris, 😄  you have really done a great job and you deserve a standing ovation 🌟 . Go ahead and merge to master and submit the project completion form. 👌 

Good luck with your next project 👍 
Happy coding

2020-02-17 20:06 UTC, merged